/**
 * Permission Constants
 * Defines all permissions available in the system
 * Permissions follow a resource_action pattern for clarity and extensibility
 */

const PERMISSIONS = {
  // Customer permissions
  CUSTOMER_READ: "CUSTOMER_READ",
  CUSTOMER_CREATE: "CUSTOMER_CREATE",
  CUSTOMER_UPDATE: "CUSTOMER_UPDATE",
  CUSTOMER_ARCHIVE: "CUSTOMER_ARCHIVE",

  // Product permissions
  PRODUCT_READ: "PRODUCT_READ",
  PRODUCT_CREATE: "PRODUCT_CREATE",
  PRODUCT_UPDATE: "PRODUCT_UPDATE",
  PRODUCT_ARCHIVE: "PRODUCT_ARCHIVE",

  // Employee permissions
  EMPLOYEE_READ: "EMPLOYEE_READ",
  EMPLOYEE_CREATE: "EMPLOYEE_CREATE",
  EMPLOYEE_UPDATE: "EMPLOYEE_UPDATE",
  EMPLOYEE_ARCHIVE: "EMPLOYEE_ARCHIVE",

  // Task permissions
  TASK_READ: "TASK_READ",
  TASK_CREATE: "TASK_CREATE",
  TASK_UPDATE: "TASK_UPDATE",
  TASK_DELETE: "TASK_DELETE",

  // Order permissions
  ORDER_READ: "ORDER_READ",
  ORDER_CREATE: "ORDER_CREATE",
  ORDER_UPDATE: "ORDER_UPDATE",
  ORDER_ARCHIVE: "ORDER_ARCHIVE",

  // Quotation permissions
  QUOTATION_READ: "QUOTATION_READ",
  QUOTATION_CREATE: "QUOTATION_CREATE",
  QUOTATION_UPDATE: "QUOTATION_UPDATE",
  QUOTATION_SUBMIT: "QUOTATION_SUBMIT",
  QUOTATION_APPROVE: "QUOTATION_APPROVE",
  QUOTATION_REJECT: "QUOTATION_REJECT",
  QUOTATION_ARCHIVE: "QUOTATION_ARCHIVE",

  // Dashboard permissions
  DASHBOARD_READ: "DASHBOARD_READ",
};

module.exports = PERMISSIONS;
